server:
  port: 8084

spring:
  application:
    name: user_service

  datasource:
    url: jdbc:postgresql://localhost:49156/user_table
    username: ewerton
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


# Eureka-Client Setup
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
